package stock.ApplicationModule;

import javax.faces.application.FacesMessage;

import javax.faces.context.FacesContext;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 03 00:20:05 AST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for ItemsView1.
     * @return ItemsView1
     */
    public ViewObjectImpl getItemsView1() {
        return (ViewObjectImpl) findViewObject("ItemsView1");
    }

    /**
     * Container's getter for ItemsView2.
     * @return ItemsView2
     */
    public ViewObjectImpl getItemsView2() {
        return (ViewObjectImpl) findViewObject("ItemsView2");
    }

    /**
     * Container's getter for ItemTypesView1.
     * @return ItemTypesView1
     */
    public ViewObjectImpl getItemTypesView1() {
        return (ViewObjectImpl) findViewObject("ItemTypesView1");
    }

    /**
     * Container's getter for ItemTypesView2.
     * @return ItemTypesView2
     */
    public ViewObjectImpl getItemTypesView2() {
        return (ViewObjectImpl) findViewObject("ItemTypesView2");
    }

    /**
     * Container's getter for UnitName1.
     * @return UnitName1
     */
    public ViewObjectImpl getUnitName1() {
        return (ViewObjectImpl) findViewObject("UnitName1");
    }

    @Override
    public void afterCommit(TransactionEvent transactionEvent) {
     
        super.afterCommit(transactionEvent);
        
        FacesMessage mesg = new FacesMessage(" „ «·Õ›Ÿ »‰Ã«Õ");
        FacesContext.getCurrentInstance().addMessage(null,mesg);
    }

    /**
     * Container's getter for VItemTranRO1.
     * @return VItemTranRO1
     */
    public ViewObjectImpl getVItemTranRO1() {
        return (ViewObjectImpl) findViewObject("VItemTranRO1");
    }

    /**
     * Container's getter for BlockSearchVItemTran1.
     * @return BlockSearchVItemTran1
     */
    public ViewObjectImpl getBlockSearchVItemTran1() {
        return (ViewObjectImpl) findViewObject("BlockSearchVItemTran1");
    }

    /**
     * Container's getter for ItemListOfValue1.
     * @return ItemListOfValue1
     */
    public ViewObjectImpl getItemListOfValue1() {
        return (ViewObjectImpl) findViewObject("ItemListOfValue1");
    }

    /**
     * Container's getter for branchesListOfValue1.
     * @return branchesListOfValue1
     */
    public ViewObjectImpl getbranchesListOfValue1() {
        return (ViewObjectImpl) findViewObject("branchesListOfValue1");
    }
}

