INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_TAX_BILLS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_TAX_BILLS', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TREE_SETTING_ACCOUNT', 'TREE_SETTING_ACCOUNT', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TREE_SETTING_ACCOUNT', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_FRIST_DATE', 'ITEM_FRIST_DATE', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_FRIST_DATE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DATE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DATE', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DATE', 'BILL_DETAIL1', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_MENU', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_MENU', 'ORDER_MENU_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_MENU', 'ORDER_MENU', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_ORDER_MENU', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_ORDER_MENU', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_ORDER_MENU', 'ORDER_MENU', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_SERVICE_CHECK', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_SERVICE_CHECK', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_SERVICE_CHECK', 'BILL_DETAIL1', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'HOTEL', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'HOTEL', 'HOTEL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'HOTEL', 'HOTEL1', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_HOTEL', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_HOTEL', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_HOTEL', 'BILL_HOTEL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'HOTEL_ITEMS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'HOTEL_ITEMS', 'HOTEL_ITEMS', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BASIC_SALARY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BASIC_SALARY', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BASIC_SALARY', 'BASIC_SALARY', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL__BAD_CUSTOMER', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL__BAD_CUSTOMER', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL__BAD_CUSTOMER', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_BAD_VENDORS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_BAD_VENDORS', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_BAD_VENDORS', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_CUSTOMER_WASHING', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_CUSTOMER_WASHING', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_CUSTOMER_WASHING', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_DAMAGE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_DAMAGE', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_DAMAGE', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_PURCHASE_CUSTOMERS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_PURCHASE_CUSTOMERS', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_PURCHASE_CUSTOMERS', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_SALE_VENDORS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_SALE_VENDORS', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_SALE_VENDORS', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_VENDORS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_VENDORS', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BILL_VENDORS', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BRANCHES', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'BRANCHES', 'BRANCHES', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'CUSTOMERS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'CUSTOMERS', 'CUSTOMERS', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'EMPLOYEES', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'EMPLOYEES', 'EMPLOYEES', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'EXTRA_SALARY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'EXTRA_SALARY', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'EXTRA_SALARY', 'EXTRA_SALARY', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'GARD_ITEMS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'GARD_ITEMS', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'GARD_ITEMS', 'STOCK_DATA', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_CHECK', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_CHECK', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_CHECK', 'V_ITEM_TRAN', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_TYPES', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_TYPES', 'ITEM_TYPES', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEMS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEMS', 'ITEMS', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'MINUS_SALARY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'MINUS_SALARY', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'MINUS_SALARY', 'MINUS_SALARY', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'RESTRICTION', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'RESTRICTION', 'RESTRICTION_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'RESTRICTION', 'RESTRICTION_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SALARY_CALCULATE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SALARY_CALCULATE', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TRANSACTION', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TRANSACTION', 'TRANSACTION', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TRANSFERS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TRANSFERS', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TRANSFERS', 'TRANSFER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TREE_ACCOUNT', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'TREE_ACCOUNT', 'RESTRICTION_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_CUSTOMER_TRAN', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_CUSTOMER_TRAN', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_CUSTOMER_TRAN', 'V_CUSTOMER_TRAN', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_VENDOR_TRAN', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_VENDOR_TRAN', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_VENDOR_TRAN', 'V_VENDOR_TRAN', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'VENDORS', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'VENDORS', 'VENDORS', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PERMISSION', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PERMISSION', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PERMISSION', 'USER_ID', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_ENT_MON', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_ENT_MON', 'V_ENT_MON', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_ALL', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_ALL', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_ALL', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_CODE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_CODE', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_CODE', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'STATEMENT_RESTRICTION', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'STATEMENT_RESTRICTION', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'STATEMENT_RESTRICTION', 'RESTRICTION_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_NOT_PAY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_NOT_PAY', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_NOT_PAY', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_PAY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_PAY', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY_PAY', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SEARCH_BILL_DAILY', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SERVICE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'SERVICE', 'SERVICE', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_TYPES_SERVICE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEM_TYPES_SERVICE', 'ITEM_TYPES_SERVICE', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEMS_SERVICE', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ITEMS_SERVICE', 'ITEMS_SERVICE', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_PAY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_PAY', 'BILL_MASTER', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'ORDER_PAY', 'BILL_DETAIL', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PRICE_LIST', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PRICE_LIST', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'PRICE_LIST', 'PRICE_LIST', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'COMPNY', 'COMPNY', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'COMPNY', 'TOOLBAR', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_TAX_TOTAL_ALL', 'SEARCH', NULL); 
INSERT INTO BLOCKS ( PROG_CODE, BLOCK_CODE, BLOCK_NAME ) VALUES ( 
'V_TAX_TOTAL_ALL', 'TOOLBAR', NULL); 
commit;
 
