ALTER TABLE BILL_DETAIL ADD(TAX   NUMBER(10) DEFAULT 5   )

---------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_BILLS
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, TOT_BEFOR_TAX, TAX, 
 TOT_AFERT_TAX, NOTES, FLAG, BRANCH_CODE)
AS 
select BILL_CODE, BILL_DATE, cus_name ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„»Ì⁄« ',1,branch_code
from bill_master,customers
where flag =1
and customers.cus_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, cus_name ,branch_code

union 

select BILL_CODE, BILL_DATE, cus_name  ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„—œÊ«  «·„»Ì⁄«  ',2,branch_code
from bill_master,customers
where flag =2 
and customers.cus_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, cus_name ,branch_code

union 

select BILL_CODE, BILL_DATE, ven_name ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'«·„‘ —Ì«   ',3,branch_code
from bill_master,vendors
where flag =3 
and vendors.ven_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, ven_name ,branch_code

union 

select BILL_CODE, BILL_DATE,  ven_name,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„—œÊ«  «·„‘ —Ì«    ',5,branch_code
from bill_master,vendors
where flag =5 
and vendors.ven_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE,  ven_name ,branch_code
/


-------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_BUY
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, VEN_NAME,BRANCH_CODE, ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL,VENDORS
WHERE FLAG=3
AND VENDORS.VEN_CODE =  BILL_DETAIL.CUS_VEN_CODE
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST, ITEM_CODE,VEN_NAME
/
-------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_RE_BUY
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, VEN_NAME,BRANCH_CODE, ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL,VENDORS
WHERE FLAG=5
AND VENDORS.VEN_CODE =  BILL_DETAIL.CUS_VEN_CODE
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST, ITEM_CODE,VEN_NAME
/


-------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_RE_SALE
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL
WHERE FLAG=2
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST,ITEM_CODE
/


--------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_SALE
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL
WHERE FLAG=1
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST,ITEM_CODE
/


---------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, ITEM_CODE, TOT_BEFOR_TAX, 
 TAX, TOT_AFERT_TAX, NOTES, FLAG, BRANCH_CODE)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„»Ì⁄« ',1,BRANCH_CODE
FROM V_TAX_SALE 

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„—œÊœ«  «·„»Ì⁄« ',2,BRANCH_CODE
FROM V_TAX_RE_SALE  

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'«·„‘ —Ì«  ',3,BRANCH_CODE
FROM V_TAX_BUY

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„—œÊ«  «·„‘ —Ì«  ',5,BRANCH_CODE
FROM V_TAX_RE_BUY
/


----------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_ALL
(TOT_SALE, TOT_BUY, SAFI, BRANCH_CODE, YEARS)
AS 
SELECT round(TOT_SALE,1),round(TOT_BUY,1), round((TOT_SALE-TOT_BUY),1),V_TAX_TOTAL_SALE_ALL.BRANCH_CODE,V_TAX_TOTAL_SALE_ALL.YEARS
FROM V_TAX_TOTAL_SALE_ALL,V_TAX_TOTAL_BUY_ALL
/


---------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_BUY_ALL
(TOT_BUY, BRANCH_CODE, BILL_DATE)
AS 
SELECT SUM(V_TAX_BUY.TAX) - SUM(V_TAX_RE_BUY.TAX) ,V_TAX_BUY.BRANCH_CODE ,V_TAX_BUY.BILL_DATE
FROM V_TAX_BUY,V_TAX_RE_BUY

GROUP BY V_TAX_BUY.BRANCH_CODE ,V_TAX_BUY.BILL_DATE
/


----------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_SALE_ALL
(TOT_SALE, BRANCH_CODE, YEARS)
AS 
SELECT SUM(V_TAX_SALE.TAX) - SUM(V_TAX_RE_SALE.TAX) ,V_TAX_SALE.BRANCH_CODE ,TO_CHAR(V_TAX_SALE.BILL_DATE,'YYYY') 
FROM V_TAX_SALE,V_TAX_RE_SALE

GROUP BY V_TAX_SALE.BRANCH_CODE ,TO_CHAR(V_TAX_SALE.BILL_DATE,'YYYY')
/


-------------------------------------------------
CREATE OR REPLACE VIEW V_TOT_TAX
(BILL_DATE, BRANCH_CODE, SUM_BEFOR_TAX, SUM_TAX, TYP, 
 FLAG)
AS 
SELECT BILL_DATE,BRANCH_CODE ,SUM(TOT_BEFOR_TAX),SUM(TAX) ,'÷—Ì»Â ·ﬁÌ„… «·„÷«›… ⁄·Ï «·„»Ì⁄« ',1
FROM V_TAX_SALE
GROUP BY BILL_DATE,BRANCH_CODE
UNION
SELECT BILL_DATE,BRANCH_CODE,SUM(TOT_BEFOR_TAX) ,SUM(TAX) ,'÷—Ì»Â ·ﬁÌ„… «·„÷«›… ⁄·Ï „—œÊ«  «·„»Ì⁄« ',2
FROM V_TAX_RE_SALE
GROUP BY BILL_DATE,BRANCH_CODE
UNION 
SELECT BILL_DATE,BRANCH_CODE ,SUM(TOT_BEFOR_TAX),SUM(TAX) ,'÷—Ì»Â ·ﬁÌ„… «·„÷«›… ⁄·Ï «·„‘ —Ì« ',3
FROM V_TAX_BUY
GROUP BY BILL_DATE,BRANCH_CODE
UNION 
SELECT BILL_DATE,BRANCH_CODE,SUM(TOT_BEFOR_TAX) ,SUM(TAX) ,'÷—Ì»Â ·ﬁÌ„… «·„÷«›… ⁄·Ï „—œÊœ«  «·„‘ —Ì« ',5
FROM V_TAX_RE_BUY
GROUP BY BILL_DATE,BRANCH_CODE
/




