INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'V_TAX_BILLS', ' ﬁ—Ì— „ÿ«·»… ÷—Ì»… «·ﬁÌ„Â «·„÷«›… »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU006'
, 50, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TREE_SETTING_ACCOUNT', '«⁄œ«œ«  «·ﬁÌÊœ', 'MENU1', 'MENU001', 49, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'ITEM_FRIST_DATE', '»÷«⁄… «Ê· «·„œ…', 'MENU1', 'MENU003', 44, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BRANCHES', '»Ì«‰«  «·›—Ê⁄', 'MENU1', 'MENU001', 1, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EMPLOYEES', '»Ì«‰«  «·„ÊŸ›Ì‰', 'MENU1', 'MENU001', 2, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'CUSTOMERS', '»Ì«‰«  «·⁄„·«¡', 'MENU1', 'MENU001', 3, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'VENDORS', '»Ì«‰«  «·„Ê—œÌ‰', 'MENU1', 'MENU001', 4, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXP', '«·‰”Œ… «·√Õ Ì«ÿÌ…', 'MENU1', 'MENU001', 8, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'ITEM_TYPES', '√‰Ê«⁄ «·√’‰«›', 'MENU001', 'ITEM_MENU', 5, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'ITEMS', '«·√’‰«›', 'MENU001', 'ITEM_MENU', 6, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'ITEM_CHECK', 'ﬂ‘› Õ—ﬂ… ’‰›', 'MENU001', 'ITEM_MENU', 7, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TRANSFERS', '«· ÕÊÌ· »Ì‰ «·„Œ«“‰', 'MENU1', 'MENU003', 15, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GARD_ITEMS', 'Ã—œ «·„Œ“‰', 'MENU1', 'MENU003', 16, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_DAMAGE', ' ”ÃÌ· »Ì«‰«  «· Ê«·›', 'MENU1', 'MENU003', 17, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TRANSACTION', 'Õ—ﬂ«  «·ﬁ»÷ Ê«·’—›', 'MENU1', 'MENU004', 18, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'V_CUSTOMER_TRAN', 'ﬂ‘› Õ”«» ⁄„Ì·', 'MENU1', 'MENU004', 19, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'V_VENDOR_TRAN', 'ﬂ‘› Õ”«» „Ê—œ', 'MENU1', 'MENU004', 20, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TREE_ACCOUNT', '‘Ã—… «·Õ”«»« ', 'MENU1', 'MENU004', 21, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'RESTRICTION', '«·ﬁÌÊœ «·ÌÊ„Ì…', 'MENU1', 'MENU004', 22, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BASIC_SALARY', '»Ì«‰«  —Ê« » «·„ÊŸ›Ì‰', 'MENU1', 'MENU005', 23, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXTRA_SALARY', '≈÷«›Ï «·„ÊŸ›Ì‰', 'MENU1', 'MENU005', 24, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MINUS_SALARY', 'Œ’Ê„«  «·„ÊŸ›Ì‰', 'MENU1', 'MENU005', 25, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'SALARY_CALCULATE', 'Õ”«» «·„— »', 'MENU1', 'MENU005', 26, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'SALARY_REP', ' ﬁ—Ì— «·„— »« ', 'MENU1', 'MENU006', 27, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EMP_REBH_REP', '√—»«Õ ÊŒ”«∆— «·„ÊŸ›Ì‰', 'MENU1', 'MENU006', 28, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REP_QUAN', ' ﬁ«—Ì— «·√’‰«›', 'MENU1', 'MENU006', 29, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_QUAN_REPORT', ' ﬁ«—Ì— ﬂ„Ì«  √’‰«› «·›Ê« Ì—', 'MENU1', 'MENU006', 30, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_TOTAL_REPORT', ' ﬁ«—Ì— ≈Ã„«·Ì«  «·›Ê« Ì—', 'MENU1', 'MENU006', 31, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_TOTAL_VENDORS', ' ﬁ—Ì— ≈Ã„«·Ï ﬁÌ„… «·›Ê« Ì— ⁄·Ï Õ”» „Ê—œ/⁄„Ì·', 'MENU1', 'MENU006'
, 32, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_VENDORS', '„‘ —Ì«  „‰ „Ê—œ', 'MENU002', 'VENDOR_MENU', 9, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_PURCHASE_CUSTOMERS', '„‘ —Ì«  „‰ ⁄„Ì·', 'MENU002', 'VENDOR_MENU', 10, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_BAD_VENDORS', '›Ê« Ì— „— Ã⁄ «·„‘ —Ì« ', 'MENU002', 'VENDOR_MENU', 11, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PERMISSION', '≈œ«—… «·‰Ÿ«„', 'MENU1', 'MENU001', 33, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'STATEMENT_RESTRICTION', 'ﬂ‘› Õ”«»  ›’Ì·Ï', 'MENU1', 'MENU007', 42, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_BAD_CUSTOMER', '›Ê« Ì— „— Ã⁄ «·⁄„·«¡', 'MENU1', 'SALE_MENU', 45, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_GOODS', '«” ·«„ »÷«⁄… „‰ «·÷„«‰', 'MENU002', 'VENDOR_MENU', 47, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BILL_CUSTOMER', '›Ê« Ì— „»Ì⁄«  «·⁄„·«¡', 'MENU002', 'SALE_MENU', 13, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_PERIODS', ' ≈œŒ«· «·› —«  «·„Õ«”»Ì…', 'MENU1', 'MENU001', 49, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'LOCK_YEAR', ' › Õ Êﬁ›· ”‰… ÃœÌœÂ', 'MENU1', 'MENU001', 50, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'AHDA', '«·⁄Âœ', 'MENU1', 'MENU003', 46, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TREE_NEW', ' «·œ·Ì· «·„Õ«”»Ï ﬂ«„·', 'MENU1', 'MENU001', 51, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'OUT_GOODS', '’—› »÷«⁄… „‰ «·÷„«‰', 'MENU002', 'VENDOR_MENU', 48, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_COST_CENTER', ' ≈œŒ«· „—«ﬂ“ «· ﬂ·›…', 'MENU1', 'MENU001', 52, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'ABILITY_FIN', '√œ«—… «·‰Ÿ«„', 'MENU1', 'MENU001', 53, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_OPEN_DAILY', '≈œŒ«· «·ﬁÌœ «·«›  «ÕÏ »ÿ—ÌﬁÂ 1', 'MENU002', 'OPEN_DAILY_MENU', 54
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_OPEN_KAIDS', '≈œŒ«· «·ﬁÌœ «·«›  «ÕÏ »ÿ—ÌﬁÂ 2', 'MENU002', 'OPEN_DAILY_MENU', 55
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_DAILY', '≈œŒ«· «·ﬁÌÊœ «·ÌÊ„Ì…', 'MENU1', 'MENU002', 56, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_DAILY2', '≈œŒ«· «·ﬁÌÊœ «·ÌÊ„Ì… 2', 'MENU1', 'MENU002', 57, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TREE_EXP', '«·œ·Ì· «·„Õ«”»Ï - „’—Ê›« ', 'MENU1', 'MENU002', 58, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_DAILY_EXP2', '«·ﬁÌÊœ «·ÌÊ„Ì…-„’—Ê›« ', 'MENU1', 'MENU002', 59, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_DAILY_INCOME', '«·ﬁÌÊœ «·ÌÊ„Ì…-«Ì—«œ« ', 'MENU1', 'MENU002', 60, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'REG_DAILY_SAVE', '«·ﬁÌÊœ «·ÌÊ„Ì…-’‰œÊﬁ «·⁄ÂœÂ', 'MENU1', 'MENU002', 61, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EDIT_REG_DAILY', ' ⁄œÌ· «·ﬁÌÊœ »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU004', 62, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EDIT_REG_DAILY_NO', ' ⁄œÌ· «·ﬁÌÊœ »—ﬁ„ «·ﬁÌœ', 'MENU1', 'MENU004', 63, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EDIT_REG_DAILY_NO2', ' ⁄œÌ· «·ﬁÌÊœ »Ì‰ —ﬁ„Ì‰ ', 'MENU1', 'MENU004', 64, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP', 'ﬂ‘› Õ”«»  ›’Ì·Ï ', 'MENU1', 'MENU005', 65, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_DATE', 'ﬂ‘› Õ”«»  ›’Ì·Ï »«· «—ÌŒ ', 'MENU1', 'MENU005', 66, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GENERAL_MASTER', 'ﬂ‘› Õ”«» ≈Ã„«·Ï ', 'MENU1', 'MENU005', 67, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'TREE_ACCOUNT', '≈Ã„«·Ï ·ﬂ· Õ”«» ', 'MENU1', 'MENU005', 68, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'SEARCH_KAID_NO', '«·ﬁÌÊœ «·ÌÊ„Ì… »—ﬁ„ «·ﬁÌœ ', 'MENU005', 'SEARCH_KAID_MENU', 69
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'SEARCH_KAID_DAY', '«·ﬁÌÊœ  «·ÌÊ„Ì… »«· «—ÌŒ ', 'MENU005', 'SEARCH_KAID_MENU', 70
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'SEARCH_KAID_DATE', '«·ﬁÌÊœ »Ì‰  «—ÌŒÌ‰', 'MENU005', 'SEARCH_KAID_MENU', 71, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_SUMS', '„Ì“«‰ „—«Ã⁄Â »«·„Ã«„Ì⁄', 'MENU1', 'MENU006', 72, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_BALANCES', '„Ì“«‰ „—«Ã⁄Â »«·«—’œÂ', 'MENU1', 'MENU006', 73, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_DATE', '„Ì“«‰ „—«Ã⁄Â ‘Â—Ï', 'MENU1', 'MENU006', 75, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_ALL', '„Ì“«‰ „—«Ã⁄Â »«·„Ã«„Ì⁄ Ê«·«—’œÂ', 'MENU1', 'MENU006', 74, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_TWO_DATE', '„Ì“«‰ „—«Ã⁄Â »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU006', 76, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_UNTIL_DATE', '„Ì“«‰ „—«Ã⁄Â Õ Ï  «—ÌŒ „⁄Ì‰', 'MENU1', 'MENU006', 77
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_REVIEW_ACCOUNT', '„Ì“«‰ „—«Ã⁄Â ‘«„· ··Õ”«»«  «·›—⁄ÌÂ', 'MENU1', 'MENU006'
, 78, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'COST_SEARCH', 'ﬂ‘› Õ”«» „—«ﬂ“ «· ﬂ·›…  ›’Ì·Ï', 'MENU1', 'MENU007', 79, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'COST_SEARCH_DATE', 'ﬂ‘› Õ”«» „—«ﬂ“ «· ﬂ·›… »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU007', 80, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'COST_SEARCH_ALL', ' ﬂ‘› Õ”«» „—«ﬂ“ «· ﬂ·›… «Ã„«·Ï ', 'MENU1', 'MENU007', 81, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_CUSTOMERS', ' ﬂ‘› Õ”«» «·⁄„·«¡  ›’Ì·Ï ', 'MENU008', 'CUSTOMERS_QUERY_MENU'
, 82, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_DATE_CUSTOMERS', '  ﬂ‘› Õ”«» «·⁄„·«¡  ›’Ì·Ï »«· «—ÌŒ', 'MENU008', 'CUSTOMERS_QUERY_MENU'
, 84, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GENERAL_MASTER_CUSTOMERS', '  ﬂ‘› Õ”«» «·⁄„·«¡ «Ã„«·Ï ', 'MENU008', 'CUSTOMERS_QUERY_MENU'
, 85, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_SUPPLIERS', 'ﬂ‘› Õ”«» «·„Ê—œÌ‰  ›’Ì·Ï', 'MENU008', 'SUPPLIERS_QUERY_MENU'
, 86, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_DATE_SUPPLIERS', 'ﬂ‘› Õ”«» «·„Ê—œÌ‰  ›’Ì·Ï »«· «—ÌŒ', 'MNEU008', 'SUPPLIERS_QUERY_MENU'
, 87, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GENERAL_MASTER_SUPPLIER', 'ﬂ‘› Õ”«» «·„Ê—œÌ‰ ≈Ã„«·Ï', 'MENU008', 'SUPPLIERS_QUERY_MENU'
, 88, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_BANK', 'ﬂ‘› Õ”«» «·»‰ﬂ  ›’Ì·Ï', 'MENU008', 'BANK_QUERY_MENU', 89, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_DATE_BANK', 'ﬂ‘› Õ”«» «·»‰ﬂ  ›’Ì·Ï »«· «—ÌŒ', 'MENU008', 'BANK_QUERY_MENU'
, 90, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GENERAL_MASTER_BANK', 'ﬂ‘› Õ”«» «·»‰ﬂ ≈Ã„«·Ï', 'MENU008', 'GENERAL_MASTER_BANK', 91
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_SAVE', 'ﬂ‘› Õ”«» «·⁄Âœ  ›’Ì·Ï', 'MENU008', 'BOX_QUERY_MENU', 92, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MASTER_HELP_DATE_SAVE', 'ﬂ‘› Õ”«» «·⁄Âœ  ›’Ì·Ï »«· «—ÌŒ', 'MENU008', 'BOX_QUERY_MENU'
, 93, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'GENERAL_MASTER_SAVE', 'ﬂ‘› Õ”«» «·⁄Âœ ≈Ã„«·Ï', 'MENU008', 'BOX_QUERY_MENU', 94, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_NOW_DATE', '«Ì—«œ«  «·‘Â— «·Õ«·Ï', 'MENU008', 'INCOME_QUERY_MENU', 95, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_DATE', '«·«Ì—«œ«  Œ·«· ‘Â—', 'MENU008', 'INCOME_QUERY_MENU', 96, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_TWO_DATE', '«·«Ì—«œ«  Œ·«· › —…', 'MENU008', 'INCOME_QUERY_MENU', 97, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_UNTIL_DATE', '«·«Ì—«œ«  Õ Ï  «—ÌŒ „⁄Ì‰', 'MENU008', 'INCOME_QUERY_MENU', 98
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXP_NOW_DATE', '„’—Ê›«  «·‘Â— «·Õ«·Ï', 'MENU008', 'EXP_QUERY_MENU', 99, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXP_DATE', '«·„’—Ê›«  Œ·«· ‘Â—', 'MENU008', 'EXP_QUERY_MENU', 100, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXP_TWO_DATE', '«·„’—Ê›«  Œ·«· › —…', 'MENU008', 'EXP_QUERY_MENU', 101, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'EXP_UNTIL_DATE', '«·„’—Ê›«  Õ Ï  «—ÌŒ „⁄Ì‰', 'MENU008', 'EXP_QUERY_MENU', 102, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'MOTAGRA', 'Õ”«» «· ‘€Ì· Ê«·„ «Ã—Â', 'MENU1', 'MENU008', 103, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PROFITS', 'Õ”«» «·«—»«Õ Ê«·Œ”«∆—', 'MENU1', 'MENU008', 104, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'INCOME_STATEMENT_LAST', 'ﬁ«∆„… «·œŒ‹·', 'MENU1', 'MENU008', 105, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANCE_SHEET', '«·„Ì“«‰ÌÂ «·⁄„Ê„Ì…', 'MENU1', 'MENU008', 105, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PROFITS_M2', 'Õ”«» «·«—»«Õ Ê«·Œ”«∆— «·ÌœÊÌ…', 'MENU008', 'MENU_QUERY_MENU', 106, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'LIST_INCOME_M', 'ﬁ«∆„… «·œŒ· «·ÌœÊÌ…', 'MENU008', 'MENU_QUERY_MENU', 107, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'BALANC_SHEET_M2', '«·„Ì“«‰ÌÂ «·⁄„Ê„Ì… «·ÌœÊÌ…', 'MENU008', 'MENU_QUERY_MENU', 108
, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PRINT_KAID', 'ÿ»«⁄… Õ—ﬂ… «·ﬁÌÊœ', 'MENU1', 'MENU009', 109, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PRINT_KAID2', 'ÿ»«⁄… œ·Ì· «·Õ”«»« ', 'MENU1', 'MENU009', 110, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'PRINT_KAID3', 'ÿ»«⁄… œ·Ì· «·Õ”«»« 2', 'MENU1', 'MENU009', 111, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'KAIDS_DELETED', '«·ﬁÌÊœ «·„Õ–Ê›Â', 'MENU1', 'MENU010', 112, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'KAIDS_DELETED_DATE', '«·ﬁÌÊœ «·„Õ–Ê›… »«· «—ÌŒ', 'MENU1', 'MENU010', 113, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'NOT_BALANCED', '«·ﬁÌÊœ «·€Ì— „ “‰Â ', 'MENU1', 'MENU010', 114, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'NOT_BALANCED_DATE', '«·ﬁÌÊœ «·€Ì— „ “‰Â »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU010', 115, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'KAIDS_UPDATED3', '«·ﬁÌÊœ «·„⁄œ·Â ', 'MENU1', 'MENU010', 116, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'KAIDS_UPDATED3_DATE', '«·ﬁÌÊœ «·„⁄œ·Â »Ì‰  «—ÌŒÌ‰', 'MENU1', 'MENU010', 117, 2); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'COMPNY', '»Ì«‰«  «·„ƒ””…', 'MENU1', 'MENU001', 43, 1); 
INSERT INTO PROG_NAME ( PROG_CODE, PROG_NAME, PARENT_MENU, MENU_CODE, ORD,
PRO ) VALUES ( 
'V_TAX_TOTAL_ALL', ' ﬁ—Ì— »«Ã„«·Ï „ÿ«·»… ÷—Ì»… «·ﬁÌ„Â «·„÷«›… ', 'MENU1', 'MENU006'
, 51, 1); 
commit;
 
