INSERT INTO TREE_SETTING_ACCOUNT ( CUS_MAIN_ID, CUS_MAIN_NAME, CUS_BRANCH_ID, CUS_BRANCH_NAME,
VEN_MAIN_ID, VEN_MAIN_NAME, VEN_BRANCH_ID, VEN_BRANCH_NAME, TAX_MAIN_ID, TAX_MAIN_NAME,
TAX_BRANCH_ID, TAX_BRANCH_NAME, TAX_ACCOUNT_ID, TAX_ACCOUNT_NAME, PUR_MAIN_ID, PUR_MAIN_NAME,
PUR_BRANCH_ID, PUR_BRANCH_NAME, PUR_ACCOUNT_ID, PUR_ACCOUNT_NAME, SAL_MAIN_ID, SAL_MAIN_NAME,
SAL_BRANCH_ID, SAL_BRANCH_NAME, SAL_ACCOUNT_ID, SAL_ACCOUNT_NAME, RE_BUY_MAIN_ID, RE_BUY_MAIN_NAME,
RE_BUY_BRANCH_ID, RE_BUY_BRANCH_NAME, RE_BUY_ACCOUNT_ID, RE_BUY_ACCOUNT_NAME, RE_SALE_MAIN_ID,
RE_SALE_MAIN_NAME, RE_SALE_BRANCH_ID, RE_SALE_BRANCH_NAME, RE_SALE_ACCOUNT_ID, RE_SALE_ACCOUNT_NAME,
RE_DAMAGE_MAIN_ID, RE_DAMAGE_MAIN_NAME, RE_DAMAGE_BRANCH_ID, RE_DAMAGE_BRANCH_NAME,
RE_DAMAGE_ACCOUNT_ID, RE_DAMAGE_ACCOUNT_NAME ) VALUES ( 
12, '√’Ê· „ œ«Ê·…', 121, '«·⁄„·«¡', 23, '«·«· “«„«  «·„ œ«Ê·…', 231, '«·„Ê—œÌ‰', 23
, '«·«· “«„«  «·„ œ«Ê·…', 234, '„” Õﬁ«  «·÷—«∆»', 234001, '÷—Ì»Â ﬁÌ„Â „÷«›Â', 32, '«·„‘ —Ì« '
, 323, '„‘ —Ì«  ⁄«„…', 323001, '„‘ —Ì«  »÷«⁄…', 41, '«·„»Ì⁄« ', 411, '„»Ì⁄«  ⁄«„…'
, 411001, '„»Ì⁄«  «·‘—ﬂ…', 43, '„—œÊœ «·„‘ —Ì« ', 431, '„—œÊ«  «·„‘ —Ì« ', 431001
, '„—œÊ«  «·„‘ —Ì« ', 33, '„—œÊœ „»Ì⁄« ', 331, '„—œÊœ«  «·„»Ì⁄« ', 331001, '„—œÊœ«  „»Ì⁄« '
, 31, '„’«—Ì› ≈œ«—ÌÂ Ê⁄„Ê„Ì…', 318, '»÷«⁄…  «·›…', 318001, '»÷«⁄…  «·›…'); 
commit;
 
