INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BANK_QUERY_MENU', 'General_Master_bank', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1
, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'V_TAX_TOTAL_ALL', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'TREE_SETTING_ACCOUNT', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'TREE_NEW', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'REG_COST_CENTER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'ABILITY_FIN', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'OPEN_DAILY_MENU', 'REG_OPEN_DAILY', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'OPEN_DAILY_MENU', 'REG_OPEN_KAIDS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'REG_DAILY', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'REG_DAILY2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'TREE_EXP', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'REG_DAILY_EXP2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'REG_DAILY_INCOME', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU002', 'REG_DAILY_SAVE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'EDIT_REG_DAILY', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'EDIT_REG_DAILY_NO', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'EDIT_REG_DAILY_NO2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU005', 'MASTER_HELP', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU005', 'MASTER_HELP_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU005', 'GENERAL_MASTER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU005', 'TREE_ACCOUNT', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU005', 'SEARCH_KAID_MENU', 'SEARCH_KAID_NO', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU005', 'SEARCH_KAID_MENU', 'SEARCH_KAID_DAY', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU005', 'SEARCH_KAID_MENU', 'SEARCH_KAID_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_SUMS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_BALANCES', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_ALL', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_TWO_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_UNTIL_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BALANCE_REVIEW_ACCOUNT', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU007', 'COST_SEARCH', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU007', 'COST_SEARCH_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU007', 'COST_SEARCH_ALL', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'REG_PERIODS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'LOCK_YEAR', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'CUSTOMERS_QUERY_MENU', 'MASTER_HELP_CUSTOMERS', '„œÌ— «·‰Ÿ«„', '111', 1
, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'CUSTOMERS_QUERY_MENU', 'MASTER_HELP_DATE_CUSTOMERS', '„œÌ— «·‰Ÿ«„', '111'
, 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'CUSTOMERS_QUERY_MENU', 'GENERAL_MASTER_CUSTOMERS', '„œÌ— «·‰Ÿ«„', '111'
, 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'SUPPLIERS_QUERY_MENU', 'MASTER_HELP_SUPPLIERS', '„œÌ— «·‰Ÿ«„', '111', 1
, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MNEU008', 'SUPPLIERS_QUERY_MENU', 'MASTER_HELP_DATE_SUPPLIERS', '„œÌ— «·‰Ÿ«„', '111'
, 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'SUPPLIERS_QUERY_MENU', 'GENERAL_MASTER_SUPPLIER', '„œÌ— «·‰Ÿ«„', '111'
, 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BANK_QUERY_MENU', 'MASTER_HELP_BANK', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BANK_QUERY_MENU', 'MASTER_HELP_DATE_BANK', '„œÌ— «·‰Ÿ«„', '111', 1, 1
, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'GENERAL_MASTER_BANK', 'GENERAL_MASTER_BANK', '„œÌ— «·‰Ÿ«„', '111', 1, 1
, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BOX_QUERY_MENU', 'MASTER_HELP_SAVE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BOX_QUERY_MENU', 'MASTER_HELP_DATE_SAVE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1
, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'BOX_QUERY_MENU', 'GENERAL_MASTER_SAVE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1
, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'INCOME_QUERY_MENU', 'INCOME_NOW_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'INCOME_QUERY_MENU', 'INCOME_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'INCOME_QUERY_MENU', 'INCOME_TWO_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'INCOME_QUERY_MENU', 'INCOME_UNTIL_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1
, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'EXP_QUERY_MENU', 'EXP_NOW_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'EXP_QUERY_MENU', 'EXP_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'EXP_QUERY_MENU', 'EXP_TWO_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'EXP_QUERY_MENU', 'EXP_UNTIL_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU008', 'MOTAGRA', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU008', 'PROFITS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU008', 'INCOME_STATEMENT_LAST', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU008', 'BALANCE_SHEET', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'MENU_QUERY_MENU', 'PROFITS_M2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'MENU_QUERY_MENU', 'LIST_INCOME_M', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU008', 'MENU_QUERY_MENU', 'BALANC_SHEET_M2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU009', 'PRINT_KAID', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU009', 'PRINT_KAID2', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU009', 'PRINT_KAID3', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'KAIDS_DELETED', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'KAIDS_DELETED_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'NOT_BALANCED', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'NOT_BALANCED_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'KAIDS_UPDATED3', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU010', 'KAIDS_UPDATED3_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'BRANCHES', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'CUSTOMERS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'VENDORS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'EXP', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU001', 'ITEM_MENU', 'ITEM_TYPES', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU001', 'ITEM_MENU', 'ITEMS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU001', 'ITEM_MENU', 'ITEM_CHECK', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU003', 'TRANSFERS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU003', 'GARD_ITEMS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU003', 'BILL_DAMAGE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'TRANSACTION', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'V_CUSTOMER_TRAN', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'V_VENDOR_TRAN', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'REP_QUAN', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BILL_QUAN_REPORT', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BILL_TOTAL_REPORT', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'VENDOR_MENU', 'BILL_BAD_VENDORS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'SALE_MENU', 'BILL_CUSTOMER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'SALE_MENU', 'BILL_BAD_CUSTOMER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'EXP', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU001', 'ITEM_MENU', 'ITEM_TYPES', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU003', 'GARD_ITEMS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU004', 'V_CUSTOMER_TRAN', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'BILL_TOTAL_VENDORS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'PERMISSION', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'VENDOR_MENU', 'BILL_VENDORS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU001', 'COMPNY', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU003', 'ITEM_FRIST_DATE', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'SALE_MENU', 'BILL_BAD_CUSTOMER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU002', 'SALE_MENU', 'BILL_CUSTOMER', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
INSERT INTO USER_ID ( PARENT_MENU, MENU_CODE, PROG_CODE, USER_ID, USER_PASS, INST, UPD, DEL,
QRY ) VALUES ( 
'MENU1', 'MENU006', 'V_TAX_BILLS', '„œÌ— «·‰Ÿ«„', '111', 1, 1, 1, 1); 
commit;
 
