CREATE OR REPLACE VIEW V_TAX_BILLS
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, TOT_BEFOR_TAX, TAX, 
 TOT_AFERT_TAX, NOTES, FLAG, BRANCH_CODE)
AS 
select BILL_CODE, BILL_DATE, cus_name ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„»Ì⁄« ',1,branch_code
from bill_master,customers
where flag =1
and customers.cus_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, cus_name ,branch_code

union 

select BILL_CODE, BILL_DATE, cus_name  ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„—œÊ«  «·„»Ì⁄«  ',2,branch_code
from bill_master,customers
where flag =2 
and customers.cus_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, cus_name ,branch_code

union 

select BILL_CODE, BILL_DATE, ven_name ,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'«·„‘ —Ì«   ',3,branch_code
from bill_master,vendors
where flag =3 
and vendors.ven_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE, ven_name ,branch_code

union 

select BILL_CODE, BILL_DATE,  ven_name,round(sum(SAFI-SUM_TAX),1),round(sum(SUM_TAX),1),round(sum(SAFI),1),'„—œÊ«  «·„‘ —Ì«    ',5,branch_code
from bill_master,vendors
where flag =5 
and vendors.ven_code = bill_master.CUS_VEN_CODE
group by BILL_CODE, BILL_DATE,  ven_name ,branch_code
/


-----------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_BUY
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_DETAIL.BILL_CODE, BILL_DETAIL.BILL_DATE, BILL_DETAIL.CUS_VEN_CODE,BILL_DETAIL.BRANCH_CODE,BILL_DETAIL.ITEM_CODE,V_TAX_SALE.QTY,SUM(BILL_DETAIL.ITEM_COST),(SUM(V_TAX_SALE.QTY)*SUM(BILL_DETAIL.ITEM_COST)) ,    (SUM(V_TAX_SALE.QTY)*BILL_DETAIL.ITEM_COST* ITEMS.TAX_RAT) /100                               ,   (SUM(V_TAX_SALE.QTY)*SUM(BILL_DETAIL.ITEM_COST)) +(SUM(V_TAX_SALE.QTY)*BILL_DETAIL.ITEM_COST* ITEMS.TAX_RAT) /100         
FROM BILL_DETAIL,V_TAX_SALE ,ITEMS
WHERE FLAG=3
AND V_TAX_SALE.BILL_CODE = BILL_DETAIL.BILL_CODE
AND V_TAX_SALE.BILL_DATE = BILL_DETAIL.BILL_DATE

AND V_TAX_SALE.BRANCH_CODE = BILL_DETAIL.BRANCH_CODE
AND ITEMS.ITEM_CODE = BILL_DETAIL.ITEM_CODE


GROUP BY BILL_DETAIL.BILL_CODE, BILL_DETAIL.BILL_DATE, BILL_DETAIL.CUS_VEN_CODE,BILL_DETAIL.BRANCH_CODE,BILL_DETAIL.ITEM_COST,V_TAX_SALE.QTY,BILL_DETAIL.ITEM_CODE,ITEMS.TAX_RAT
/


----------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_RE_BUY
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE, ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL
WHERE FLAG=5
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST, ITEM_CODE
/
----------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_RE_SALE
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL
WHERE FLAG=2
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST,ITEM_CODE
/

-------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_SALE
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, BRANCH_CODE, ITEM_CODE, 
 QTY, PRICE, TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_CODE,SUM(ITEM_QUAN),SUM(ITEM_COST),(SUM(ITEM_QUAN)*SUM(ITEM_COST)) ,SUM(TAX_RAT),  (SUM(ITEM_QUAN)*SUM(ITEM_COST))+SUM(TAX_RAT)
FROM BILL_DETAIL
WHERE FLAG=1
GROUP BY BILL_CODE, BILL_DATE, CUS_VEN_CODE,BRANCH_CODE,ITEM_COST,ITEM_CODE
/

-------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, ITEM_CODE, TOT_BEFOR_TAX, 
 TAX, TOT_AFERT_TAX, NOTES, FLAG, BRANCH_CODE)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„»Ì⁄« ',1,BRANCH_CODE
FROM V_TAX_SALE 

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„—œÊœ«  «·„»Ì⁄« ',2,BRANCH_CODE
FROM V_TAX_RE_SALE  

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'«·„‘ —Ì«  ',3,BRANCH_CODE
FROM V_TAX_BUY

UNION 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,ITEM_CODE,TOT_BEFOR_TAX, TAX, TOT_AFERT_TAX,'„—œÊ«  «·„‘ —Ì«  ',5,BRANCH_CODE
FROM V_TAX_RE_BUY
/


------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_ALL
(TOT_SALE, TOT_BUY, SAFI, BRANCH_CODE, YEARS)
AS 
SELECT round(TOT_SALE,1),round(TOT_BUY,1), round((TOT_SALE-TOT_BUY),1),V_TAX_TOTAL_SALE_ALL.BRANCH_CODE,V_TAX_TOTAL_SALE_ALL.YEARS
FROM V_TAX_TOTAL_SALE_ALL,V_TAX_TOTAL_BUY_ALL
/

------------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_BUY_ALL
(TOT_BUY, BRANCH_CODE, YEARS)
AS 
SELECT SUM(V_TAX_BUY.TAX) - SUM(V_TAX_RE_BUY.TAX) ,V_TAX_BUY.BRANCH_CODE ,TO_CHAR(V_TAX_BUY.BILL_DATE,'YYYY') 
FROM V_TAX_BUY,V_TAX_RE_BUY

GROUP BY V_TAX_BUY.BRANCH_CODE ,TO_CHAR(V_TAX_BUY.BILL_DATE,'YYYY')
/


----------------------------------------------------------------
CREATE OR REPLACE VIEW V_TAX_TOTAL_SALE_ALL
(TOT_SALE, BRANCH_CODE, YEARS)
AS 
SELECT SUM(V_TAX_SALE.TAX) - SUM(V_TAX_RE_SALE.TAX) ,V_TAX_SALE.BRANCH_CODE ,TO_CHAR(V_TAX_SALE.BILL_DATE,'YYYY') 
FROM V_TAX_SALE,V_TAX_RE_SALE

GROUP BY V_TAX_SALE.BRANCH_CODE ,TO_CHAR(V_TAX_SALE.BILL_DATE,'YYYY')
/


----------------------------------------------------------

CREATE OR REPLACE VIEW V_VENDOR_TRAN
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, CUS_NAME, MADIN, 
 DAAN, FLAG, SRC)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,VENDORS.VEN_NAME,0,PAY_REMAIN,FLAG,'›Ê« Ì—  Ê—Ìœ«  «·„Ê—œÌ‰'
FROM BILL_MASTER,VENDORS
WHERE VENDORS.VEN_CODE=BILL_MASTER.CUS_VEN_CODE
AND FLAG=3
AND PAY_REMAIN>0
UNION

SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,VENDORS.VEN_NAME,PAY_REMAIN,0,FLAG,'›Ê« Ì— „— Ã⁄«  «·„Ê—œÌ‰'
FROM BILL_MASTER,VENDORS
WHERE VENDORS.VEN_CODE=BILL_MASTER.CUS_VEN_CODE
AND FLAG=5
AND PAY_REMAIN>0
UNION

SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,VENDORS.VEN_NAME,PAY_REMAIN,0,FLAG,'›Ê« Ì— „»Ì⁄«  «·„Ê—œÌ‰'
FROM BILL_MASTER,VENDORS
WHERE VENDORS.VEN_CODE=BILL_MASTER.CUS_VEN_CODE
AND FLAG=6
AND PAY_REMAIN>0
UNION

SELECT TRANS_CODE, TRANS_DATE,CUS_VEN_CODE,VENDORS.VEN_NAME,0, PAYED,10,'Õ—ﬂ… ﬁ»÷ „‰ „Ê—œ'
FROM TRANSACTION,VENDORS
WHERE VENDORS.VEN_CODE=TRANSACTION.CUS_VEN_CODE 
AND TRANS_TYPE=1
AND CUS_VEN_TYPE=2

UNION

SELECT TRANS_CODE, TRANS_DATE,CUS_VEN_CODE,VENDORS.VEN_NAME,PAYED,0,11,'Õ—ﬂ… ’—› «·Ï „Ê—œ'
FROM TRANSACTION,VENDORS
WHERE VENDORS.VEN_CODE=TRANSACTION.CUS_VEN_CODE 
AND TRANS_TYPE=2
AND CUS_VEN_TYPE=2
/

--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_CUSTOMER_TRAN
(BILL_CODE, BILL_DATE, CUS_VEN_CODE, CUS_NAME, MADIN, 
 DAAN, FLAG, SRC)
AS 
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,SAFI,SAFI,FLAG,'›Ê« Ì— «·⁄„·«¡ ‰ﬁœ«'
FROM BILL_MASTER,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=1
AND PAY_TYPE=1

UNION
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,SAFI,SAFI,FLAG,' ›Ê« Ì— „— Ã⁄ «·⁄„·«¡ ‰ﬁœ«'
FROM BILL_MASTER,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=2
AND PAY_TYPE=1

union 

SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,SAFI,SAFI,FLAG,'›Ê« Ì— «·⁄„·«¡ - »‰ﬂ'
FROM BILL_MASTER,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=1
AND PAY_TYPE=3

UNION
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,SAFI,SAFI,FLAG,' ›Ê«  Ì— „— Ã⁄ «·⁄„·«¡ - ‘Ìﬂ'
FROM BILL_MASTER,CUSTOMERS
WHERE  CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=2
AND PAY_TYPE=3


union 

SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,SAFI,0,FLAG,'›Ê« Ì— «·⁄„·«¡ - «Ã·'
FROM BILL_MASTER,CUSTOMERS
WHERE  CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=1
AND PAY_TYPE=2

UNION
SELECT BILL_CODE, BILL_DATE, CUS_VEN_CODE,CUSTOMERS.CUS_NAME,0,SAFI,FLAG,' ›Ê«  Ì— „— Ã⁄ «·⁄„·«¡ - «Ã·'
FROM BILL_MASTER,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TO_NUMBER(BILL_MASTER.CUS_VEN_CODE)
AND FLAG=2
AND PAY_TYPE=2


UNION
SELECT TRANS_CODE, TRANS_DATE,CUS_VEN_CODE,CUSTOMERS.CUS_NAME,0, PAYED,10,'Õ—ﬂ… ﬁ»÷ „‰ ⁄„Ì·'
FROM TRANSACTION,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TRANSACTION.CUS_VEN_CODE
AND TRANS_TYPE=1
AND CUS_VEN_TYPE=1

UNION
SELECT TRANS_CODE, TRANS_DATE,CUS_VEN_CODE,CUSTOMERS.CUS_NAME,PAYED,0,11,'Õ—ﬂ… ’—› «·Ï ⁄„Ì·'
FROM TRANSACTION,CUSTOMERS
WHERE CUSTOMERS.CUS_CODE=TRANSACTION.CUS_VEN_CODE
AND TRANS_TYPE=2
AND CUS_VEN_TYPE=1
/







